---
- hosts: all
  any_errors_fatal: false
  environment:
    NETRC: ''

  roles:
    - role: bodsch.monitoring_plugins

  pre_tasks:
    - name: python version
      debug:
        msg:
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"

  post_tasks:
    - name: python version
      debug:
        msg:
          - "python version       : {{ ansible_python.version.major }}.{{ ansible_python.version.minor }}"
