---
- hosts: all
  roles:
    - oefenweb.postfix
  vars:
    postfix_aliases:
      - user: root
        alias: alexg@grigoryev.eu
      - user: john
        alias: john@grigoryev.eu
      - user: gordon
        alias: gordon@grigoryev.eu
      - user: psst
        alias: psst@grigoryev.eu